/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../components/AppButton.vue')['default']
    ArticleCard: typeof import('./../components/ArticleCard.vue')['default']
    LayoutContainer: typeof import('./../components/LayoutContainer.vue')['default']
    PersonAvatar: typeof import('./../components/PersonAvatar.vue')['default']
    PersonBadge: typeof import('./../components/PersonBadge.vue')['default']
    PersonCard: typeof import('./../components/PersonCard.vue')['default']
  }
}
