name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.3"]
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install PHP Dependencies
        run: composer update --ignore-platform-req=php+ --no-interaction --no-progress
      - name: Install Node.js Dependencies
        run: |
          npm ci
      # waits for https://github.com/fsr5-fhaachen/strichlistensystem/issues/99
      # - name: Execute Node.js linting
      #   run: |
      #     npm run lint
      # - name: Execute PHP linting
      #   run: |
      #     ./vendor/bin/pint
      - name: Execute build
        run: npm run build --if-present
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan migrate
      - name: Execute seeders
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan db:seed
      # - name: Execute tests (Unit and Feature tests) via PHPUnit
      #   env:
      #     DB_CONNECTION: sqlite
      #     DB_DATABASE: database/database.sqlite
      #   run: vendor/bin/phpunit
